# Generated by Django 4.2.6 on 2023-11-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DroneConesApp", "populate"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="commissions",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="drones",
            field=models.ManyToManyField(blank=True, to="DroneConesApp.drone"),
        ),
    ]
