# Generated by Django 4.2.6 on 2023-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneConesApp', '0002_cone_drone_ice_cream_order_order_item_topping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
