# Generated by Django 4.1.6 on 2023-11-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneConesApp', '0003_order_item_total'),
        ('DroneConesApp', 'populate'),
    ]

    operations = [
    ]
