# Generated by Django 4.1.6 on 2023-11-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneConesApp', '0004_merge_0003_order_item_total_populate'),
        ('DroneConesApp', '0006_remove_help_request_user_id'),
    ]

    operations = [
    ]
