# Generated by Django 4.1.7 on 2023-11-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneConesApp', '0004_shipping_address_billing_address'),
        ('DroneConesApp', '0007_merge_20231106_1750'),
    ]

    operations = [
    ]
