# Generated by Django 4.2.6 on 2023-11-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneConesApp', '0004_shipping_address_billing_address'),
        ('DroneConesApp', '0007_merge_20231106_1750'),
    ]

    operations = [
    ]
